//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourAgency.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public int id { get; set; }
        public string hotelName { get; set; }
        public int countOfStars { get; set; }
        public int countryCode { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual HotelComment HotelComment { get; set; }
        public virtual HotelImage HotelImage { get; set; }
        public virtual HotelTour HotelTour { get; set; }
    }
}
